KZOO-308 Functionality to Intercept Users According to CALEA Intercept Requests
2600hz/kazoo-media-mgr pull request #32
Opened 2023-03-13 19:41 UTC by nkarunarathne

Previously, there was no option to tap users according to CALEA intercept requests.

This change will allow wiretap recordings to save along with other recording types without impacting existing functionality.

2023-03-29 19:16 UTC, icehess requested changes

2023-03-29 19:16 UTC, icehess commented on src/media_recording.erl
> +maybe_store_recording(Media, Store, Pid) ->
We don't like binding variables this way in different case clasues. Instead update store in a separate function like this:


```erlang
save_recording(#{media := Media, pid := Pid}=Store) ->
    UpdatedStore = maybe_add_wiretap_info(Store),
    case maybe_store_recording_meta(UpdatedStore) of
        {'error', Err} ->
            lager:warning("error storing metadata : ~p", [Err]),
            gen_server:cast(Pid, {'store_failed', UpdatedStore});
        Rev ->
            StoreUrl = fun()-> store_url(UpdatedStore, Rev) end,
            store_recording(Media, StoreUrl, UpdatedStore)
    end.

-spec maybe_add_wiretap_info(store_info()) -> store_info().
maybe_add_wiretap_info(#{event:= Event}=Store) ->
    case kz_json:is_true([<<"Recording">>, <<"Is-Wiretap">>], Event, 'false') of
        'false' -> Store;
        'true' -> update_wiretap_store_info(Store)
    end.

```

2023-03-29 19:16 UTC, icehess commented on src/media_recording.erl
> +    UpdatedStoreInfo.
You don't need to match on all maps keys and re-add them, just binding to var and update the only the fields you want to update:

```suggestion
-spec update_wiretap_store_info(store_info()) -> store_info().
update_wiretap_store_info(Store) ->
    Store#{doc_db => ?WIRETAP_DB
          ,should_store => get_should_store()
          ,retries => ?WIRETAP_STORAGE_RETRY_TIMES
          }.
```

2023-03-29 19:16 UTC, icehess commented on src/media_recording.erl
> +    case kapps_config:get(?CONFIG_CAT ,<<"wiretap_should_store">>, <<"local">>) of
```suggestion
    case kapps_config:get_ne_binary(?CONFIG_CAT ,<<"wiretap_should_store">>, <<"local">>) of
```

2023-11-09 15:35 UTC, nkarunarathne commented
Not relevant now

2023-11-09 15:35 UTC, closed without merging